# Cloud Build configuration for MP Writer Backend API
#
# Required substitution variables (set in Cloud Build trigger):
#   _MONGO_URI             - MongoDB connection string
#   _REDIS_URL             - Redis connection string (e.g., redis://your-redis:6379)
#   _JWT_SECRET            - JWT signing secret (min 32 chars, generate with: openssl rand -hex 32)
#   _DATA_ENCRYPTION_KEY   - Data encryption key (generate with: openssl rand -hex 32)
#   _OPENAI_API_KEY        - OpenAI API key
#   _APP_ORIGIN            - Frontend URL (e.g., https://your-frontend.run.app)
#   _SERVICE_NAME          - Cloud Run service name (default: mp-writer-production-backend)
#   _REGION                - Cloud Run region (default: europe-west1)
#
# Optional Stripe variables:
#   _STRIPE_CHECKOUT_ENABLED      - Set to "1" to enable Stripe checkout (default: 0)
#   _STRIPE_SECRET_KEY            - Stripe secret key (required if checkout enabled)
#   _STRIPE_WEBHOOK_SECRET        - Stripe webhook secret (required if checkout enabled)
#   _STRIPE_CURRENCY              - Stripe currency code (default: gbp)
#   _STRIPE_PRICE_ID_CREDITS_3    - Stripe price ID for 3 credits package
#   _STRIPE_PRICE_ID_CREDITS_6    - Stripe price ID for 6 credits package
#   _STRIPE_PRICE_ID_CREDITS_12   - Stripe price ID for 12 credits package
#   _STRIPE_AMOUNT_CREDITS_3      - Amount in pence for 3 credits (e.g., 300 = £3.00)
#   _STRIPE_AMOUNT_CREDITS_6      - Amount in pence for 6 credits
#   _STRIPE_AMOUNT_CREDITS_12     - Amount in pence for 12 credits
#
# Optional OAuth variables:
#   _GOOGLE_CLIENT_ID             - Google OAuth client ID
#   _GOOGLE_CLIENT_SECRET         - Google OAuth client secret
#   _GOOGLE_CALLBACK_URL          - Google OAuth callback URL
#
# Optional OpenAI model configuration:
#   _OPENAI_MODEL                 - Default model (default: gpt-4o-mini)
#   _OPENAI_TRANSCRIPTION_MODEL   - Transcription model (default: gpt-4o-mini-transcribe)
#   _OPENAI_FOLLOW_UP_MODEL       - Follow-up model (default: gpt-5-mini)
#   _OPENAI_LETTER_MODEL          - Letter generation model (default: gpt-5)
#   _OPENAI_LETTER_VERBOSITY      - Letter verbosity: low/medium/high (default: medium)
#   _OPENAI_LETTER_REASONING_EFFORT - Reasoning effort: low/medium/high (default: high)
#   _OPENAI_DEEP_RESEARCH_MODEL   - Deep research model (default: o4-mini-deep-research)
#   _OPENAI_DEEP_RESEARCH_ENABLE_WEB_SEARCH - Enable web search (default: true)
#   _OPENAI_DEEP_RESEARCH_WEB_SEARCH_CONTEXT_SIZE - Web search context size
#   _OPENAI_DEEP_RESEARCH_VECTOR_STORE_IDS - Comma-separated vector store IDs
#   _OPENAI_DEEP_RESEARCH_ENABLE_CODE_INTERPRETER - Enable code interpreter (default: false)
#   _OPENAI_DEEP_RESEARCH_MAX_TOOL_CALLS - Max tool calls per request
#   _OPENAI_DEEP_RESEARCH_REASONING_SUMMARY - Reasoning summary mode (default: auto)
#   _OPENAI_DEEP_RESEARCH_REASONING_EFFORT - Reasoning effort: low/medium/high (default: medium)
#
# Optional address lookup:
#   _GETADDRESS_API_KEY           - GetAddress.io API key for UK address lookup
#   _ADDRESS_DEBUG                - Enable address lookup debug logging (default: 0)
#
# Optional advanced settings:
#   _TRUST_PROXY                  - Trust proxy headers (default: 1 for Cloud Run)
#   _STREAMING_STATE_TTL_MS       - Streaming state TTL in milliseconds

steps:
  # 1️⃣ Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dockerfile.backend'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:latest'
      - '.'

  # 2️⃣ Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--cpu-boost'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,ALLOW_DEV_CREDIT_MUTATION=0,TRUST_PROXY=${_TRUST_PROXY},MONGO_URI=${_MONGO_URI},REDIS_URL=${_REDIS_URL},STREAMING_STATE_TTL_MS=${_STREAMING_STATE_TTL_MS},JWT_SECRET=${_JWT_SECRET},DATA_ENCRYPTION_KEY=${_DATA_ENCRYPTION_KEY},APP_ORIGIN=${_APP_ORIGIN},STRIPE_CHECKOUT_ENABLED=${_STRIPE_CHECKOUT_ENABLED},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},STRIPE_WEBHOOK_SECRET=${_STRIPE_WEBHOOK_SECRET},STRIPE_CURRENCY=${_STRIPE_CURRENCY},STRIPE_PRICE_ID_CREDITS_3=${_STRIPE_PRICE_ID_CREDITS_3},STRIPE_PRICE_ID_CREDITS_6=${_STRIPE_PRICE_ID_CREDITS_6},STRIPE_PRICE_ID_CREDITS_12=${_STRIPE_PRICE_ID_CREDITS_12},STRIPE_AMOUNT_CREDITS_3=${_STRIPE_AMOUNT_CREDITS_3},STRIPE_AMOUNT_CREDITS_6=${_STRIPE_AMOUNT_CREDITS_6},STRIPE_AMOUNT_CREDITS_12=${_STRIPE_AMOUNT_CREDITS_12},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GOOGLE_CALLBACK_URL=${_GOOGLE_CALLBACK_URL},OPENAI_API_KEY=${_OPENAI_API_KEY},OPENAI_MODEL=${_OPENAI_MODEL},OPENAI_TRANSCRIPTION_MODEL=${_OPENAI_TRANSCRIPTION_MODEL},OPENAI_FOLLOW_UP_MODEL=${_OPENAI_FOLLOW_UP_MODEL},OPENAI_LETTER_MODEL=${_OPENAI_LETTER_MODEL},OPENAI_LETTER_VERBOSITY=${_OPENAI_LETTER_VERBOSITY},OPENAI_LETTER_REASONING_EFFORT=${_OPENAI_LETTER_REASONING_EFFORT},OPENAI_DEEP_RESEARCH_MODEL=${_OPENAI_DEEP_RESEARCH_MODEL},OPENAI_DEEP_RESEARCH_ENABLE_WEB_SEARCH=${_OPENAI_DEEP_RESEARCH_ENABLE_WEB_SEARCH},OPENAI_DEEP_RESEARCH_WEB_SEARCH_CONTEXT_SIZE=${_OPENAI_DEEP_RESEARCH_WEB_SEARCH_CONTEXT_SIZE},OPENAI_DEEP_RESEARCH_VECTOR_STORE_IDS=${_OPENAI_DEEP_RESEARCH_VECTOR_STORE_IDS},OPENAI_DEEP_RESEARCH_ENABLE_CODE_INTERPRETER=${_OPENAI_DEEP_RESEARCH_ENABLE_CODE_INTERPRETER},OPENAI_DEEP_RESEARCH_MAX_TOOL_CALLS=${_OPENAI_DEEP_RESEARCH_MAX_TOOL_CALLS},OPENAI_DEEP_RESEARCH_REASONING_SUMMARY=${_OPENAI_DEEP_RESEARCH_REASONING_SUMMARY},OPENAI_DEEP_RESEARCH_REASONING_EFFORT=${_OPENAI_DEEP_RESEARCH_REASONING_EFFORT},GETADDRESS_API_KEY=${_GETADDRESS_API_KEY},ADDRESS_DEBUG=${_ADDRESS_DEBUG}'

# Store built images
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:latest'

# Default values for substitution variables
substitutions:
  _SERVICE_NAME: 'mp-writer-production-backend'
  _REGION: 'europe-west1'
  _TRUST_PROXY: '1'
  _STREAMING_STATE_TTL_MS: ''
  _STRIPE_CHECKOUT_ENABLED: '0'
  _STRIPE_SECRET_KEY: ''
  _STRIPE_WEBHOOK_SECRET: ''
  _STRIPE_CURRENCY: 'gbp'
  _STRIPE_PRICE_ID_CREDITS_3: ''
  _STRIPE_PRICE_ID_CREDITS_6: ''
  _STRIPE_PRICE_ID_CREDITS_12: ''
  _STRIPE_AMOUNT_CREDITS_3: ''
  _STRIPE_AMOUNT_CREDITS_6: ''
  _STRIPE_AMOUNT_CREDITS_12: ''
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _GOOGLE_CALLBACK_URL: ''
  _OPENAI_MODEL: 'gpt-4o-mini'
  _OPENAI_TRANSCRIPTION_MODEL: 'gpt-4o-mini-transcribe'
  _OPENAI_FOLLOW_UP_MODEL: 'gpt-5-mini'
  _OPENAI_LETTER_MODEL: 'gpt-5'
  _OPENAI_LETTER_VERBOSITY: 'medium'
  _OPENAI_LETTER_REASONING_EFFORT: 'high'
  _OPENAI_DEEP_RESEARCH_MODEL: 'o4-mini-deep-research'
  _OPENAI_DEEP_RESEARCH_ENABLE_WEB_SEARCH: 'true'
  _OPENAI_DEEP_RESEARCH_WEB_SEARCH_CONTEXT_SIZE: 'medium'
  _OPENAI_DEEP_RESEARCH_VECTOR_STORE_IDS: ''
  _OPENAI_DEEP_RESEARCH_ENABLE_CODE_INTERPRETER: 'false'
  _OPENAI_DEEP_RESEARCH_MAX_TOOL_CALLS: ''
  _OPENAI_DEEP_RESEARCH_REASONING_SUMMARY: 'auto'
  _OPENAI_DEEP_RESEARCH_REASONING_EFFORT: 'medium'
  _GETADDRESS_API_KEY: ''
  _ADDRESS_DEBUG: '0'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

