# Cloud Build configuration for MP Writer Backend API
#
# Required substitution variables (set in Cloud Build trigger):
#   _MONGO_URI             - MongoDB connection string
#   _REDIS_URL             - Redis connection string (e.g., redis://your-redis:6379)
#   _JWT_SECRET            - JWT signing secret (min 32 chars, generate with: openssl rand -hex 32)
#   _DATA_ENCRYPTION_KEY   - Data encryption key (generate with: openssl rand -hex 32)
#   _OPENAI_API_KEY        - OpenAI API key
#   _APP_ORIGIN            - Frontend URL (e.g., https://your-frontend.run.app)
#   _SERVICE_NAME          - Cloud Run service name (default: mp-writer-production-backend)
#   _REGION                - Cloud Run region (default: europe-west1)
#
# Optional substitution variables:
#   _STRIPE_CHECKOUT_ENABLED      - Set to "1" to enable Stripe checkout
#   _STRIPE_SECRET_KEY            - Stripe secret key (required if checkout enabled)
#   _STRIPE_WEBHOOK_SECRET        - Stripe webhook secret (required if checkout enabled)
#   _STRIPE_PRICE_ID_CREDITS_3    - Stripe price ID for 3 credits
#   _STRIPE_PRICE_ID_CREDITS_6    - Stripe price ID for 6 credits
#   _STRIPE_PRICE_ID_CREDITS_12   - Stripe price ID for 12 credits
#   _GOOGLE_CLIENT_ID             - Google OAuth client ID (optional)
#   _GOOGLE_CLIENT_SECRET         - Google OAuth client secret (optional)
#   _GOOGLE_CALLBACK_URL          - Google OAuth callback URL (optional)
#   _GETADDRESS_API_KEY           - GetAddress.io API key for UK address lookup (optional)

steps:
  # 1️⃣ Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dockerfile.backend'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:$SHORT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:latest'
      - '.'

  # 2️⃣ Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,ALLOW_DEV_CREDIT_MUTATION=0,MONGO_URI=${_MONGO_URI},REDIS_URL=${_REDIS_URL},JWT_SECRET=${_JWT_SECRET},DATA_ENCRYPTION_KEY=${_DATA_ENCRYPTION_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY},APP_ORIGIN=${_APP_ORIGIN},STRIPE_CHECKOUT_ENABLED=${_STRIPE_CHECKOUT_ENABLED},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},STRIPE_WEBHOOK_SECRET=${_STRIPE_WEBHOOK_SECRET},STRIPE_PRICE_ID_CREDITS_3=${_STRIPE_PRICE_ID_CREDITS_3},STRIPE_PRICE_ID_CREDITS_6=${_STRIPE_PRICE_ID_CREDITS_6},STRIPE_PRICE_ID_CREDITS_12=${_STRIPE_PRICE_ID_CREDITS_12},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GOOGLE_CALLBACK_URL=${_GOOGLE_CALLBACK_URL},GETADDRESS_API_KEY=${_GETADDRESS_API_KEY}'

# Store built images
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:$SHORT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mpwriter-repo/mpwriter-backend:latest'

# Default values for substitution variables
substitutions:
  _SERVICE_NAME: 'mp-writer-production-backend'
  _REGION: 'europe-west1'
  _STRIPE_CHECKOUT_ENABLED: ''
  _STRIPE_SECRET_KEY: ''
  _STRIPE_WEBHOOK_SECRET: ''
  _STRIPE_PRICE_ID_CREDITS_3: ''
  _STRIPE_PRICE_ID_CREDITS_6: ''
  _STRIPE_PRICE_ID_CREDITS_12: ''
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _GOOGLE_CALLBACK_URL: ''
  _GETADDRESS_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

